

class Application_Format:
    def __init__(self):
        self.company = company
        self.title = title
        self.date = date
        self.status = status
        self.email = email
        self.notes = notes

    def format(self):
        return[self.company, self.title, self.date, self.status, self.email, self.notes]

class Opperations:

    def add_app(self):

        print("Add")
        
    def view_app(self):

        print("View")

    def search_app(self):

        print("Search")

    def update_app(self):

        print("Update")

    def save_app(self):

        print("Save")

    def load_app(self):

        print("Load")

def main():

    Changes = Opperations()

    while True:                              # Loops the code indefinitely, unless exit option is entered

        print("---MENU---")                      # Menu options
        print("1. Add Job Application ")
        print("2. View Job Application(s) ")
        print("3. Search For Job Application(s) ")
        print("4. Update Job Application ")
        print("5. Save Job Applications to file ")
        print("6. Download Job Applications from file ")
        print("7. Exit ")
        option = input("Please enter your option. ")

        if option == "1":                    # Chooses the definition within the Tracker class to run dependant on the option chosen
            Changes.add_app()
        elif option == "2":
            Changes.view_app()
        elif option == "3":
            Changes.search_app()
        elif option == "4":
            Changes.update_app()
        elif option == "5":
            Changes.save_app()
        elif option == "6":
            Changes.load_app()
        elif option == "7":
            break
        else:
            print("Invalid choice")

if __name__ == "__main__":
    main()

'''
NOTE: Program idea was generated by ChatGPT, but all code is "hand" written.
      ChatGPT prompt: "What is a possble useful application for Regex, Testing, Libraries, File I/O, and OOP functions?"

Step by step process:
    Create / find Job_Applications.csv for storing data
    Have a menu system for each option:
        Add Job Application
            Company Name
            Job Title
            Application Date
            Status (Applied / Interview / Offer / Rejected)
            Email Contact
            Notes
        View Job Applications (All data)
        Search Job Applications (Ideally by any data point, however by Status at minimum)
        Update Job Applications
        Save (Upload to CSV file) Job Applications
        Load (Extract from CSV file) Job Applications
        Exit
    
    The code must also be able to Validate inputs to ensure they are acceptable and make logical sense'''