import csv

class Tracker:
    def add_app(self): #app == application

        print()


def main():

    Tracker = Tracker()

    print("---MENU---")                      # Menu options
    print("1. Add Job Application ")
    print("2. View Job Application(s) ")
    print("3. Search For Job Application(s) ")
    print("4. Update Job Application ")
    print("5. Save Job Applications to file ")
    print("6. Download Job Applications from file ")
    print("7. Exit ")
    option = input("Please enter your option. ")

    while True:                              # Loops the code indefinitely, unless exit option is entered

        if option == "1":                    # Chooses the definition within the Tracker class to run dependant on the option chosen
            Tracker.add_app()
        elif option == "2":
            Tracker.view_app()
        elif option == "3":
            Tracker.search()
        elif option == "4":
            Tracker.update_app()
        elif option == "5":
            Tracker.save()
        elif option == "6":
            Tracker.load()
        elif option == "7":
            break
        else:
            print("Invalid choice")

if __name__ == "__main__":
    main()

'''
NOTE: Program idea was generated by ChatGPT, but all code is "hand" written.
      ChatGPT prompt: "What is a possble useful application for Regex, Testing, Libraries, File I/O, and OOP functions?"

Step by step process:
    Create / find Job_Applications.csv for storing data
    Have a menu system for each option:
        Add Job Application
            Company Name
            Job Title
            Application Date
            Status (Applied / Interview / Offer / Rejected)
            Email Contact
            Notes
        View Job Applications (All data)
        Search Job Applications (Ideally by any data point, however by Status at minimum)
        Update Job Applications
        Save (Upload to CSV file) Job Applications
        Load (Extract from CSV file) Job Applications
        Exit
    
    The code must also be able to Validate inputs to ensure they are acceptable and make logical sense'''