import csv

def add_app(): #app == application
    

def main():

    print("---MENU---")
    print("1. Add Job Application ")
    print("2. View Job Application(s) ")
    print("3. Search For Job Application(s) ")
    print("4. Update Job Application ")
    print("5. Save Job Applications to file ")
    print("6. Download Job Applications from file ")
    option = input("7. Exit ")

if __name__ == "__main__":
    main()

'''
NOTE: Program idea was generated by ChatGPT, but all code is "hand" written.
      ChatGPT prompt: "What is a possble useful application for Regex, Testing, Libraries, File I/O, and OOP functions?"

Step by step process:
    Create / find Job_Applications.csv for storing data
    Have a menu system for each option:
        Add Job Application
            Company Name
            Job Title
            Application Date
            Status (Applied / Interview / Offer / Rejected)
            Email Contact
            Notes
        View Job Applications (All data)
        Search Job Applications (Ideally by any data point, however by Status at minimum)
        Update Job Applications
        Save (Upload to CSV file) Job Applications
        Load (Extract from CSV file) Job Applications
        Exit
    
    The code must also be able to Validate inputs to ensure they are acceptable and make logical sense'''